---
namespace: jackaltx
name: solti_platforms
version: 1.0.0
readme: README.md
authors:
  - Jackaltx <jack@jackaltx.com>

description: This creates VMs ready for provisioning
license:
  - MIT
license_file: ""
tags: []
dependencies:
  "community.general": ">=10.0.0"

repository: http://github.com/jackaltx/solti-platforms
documentation: http://docs.jackaltx.com
homepage: http://github.com/jackaltx/solti-platforms
issues: http://github.com/jackaltx/solti-platforms/issue/tracker

build_ignore: []
