---
# Platform inventory for solti-platforms collection
# Used by manage-platform.sh and platform-exec.sh
#
# IMPORTANT: Add your Proxmox server(s) to proxmox_template_platform group
# These tasks run ON the Proxmox host, not localhost

# Claude: I love the idea, but the functionality...the children at this level are "capabilities", which can be applied to a all hosts
# if we target a specic host will it get all the group vars (proxmox_storage,..)?

all:
  children:
    # Proxmox template platform
    # Add your Proxmox servers here (see ../inventory.yml for examples)
    proxmox_template_platform:
      hosts:
        magic:
      vars:
        # Proxmox configuration
        proxmox_storage: local-lvm
        proxmox_bridge: vmbr0
        template_work_dir: /opt/solti/qcow
        template_cleanup: false

    # Proxmox VM platform (Phase 2)
    proxmox_vm_platform:
      hosts:
        magic: # Uncomment and configure for your Proxmox host
      vars:
        proxmox_storage: local-lvm
        proxmox_bridge: vmbr0

    # Platform base provisioning (Phase 3)
    platform_base_platform:
      hosts:
        # Add your target hosts here
      vars:
        # Common provisioning variables

    # Linode instance platform (Phase 4)
    linode_instance_platform:
      hosts:
        localhost:
          ansible_connection: local
      vars:
        # Linode API configuration

    # K3s control plane (Phase 5)
    k3s_control_platform:
      hosts:
        # Add your k3s control plane hosts here
      vars:
        # K3s control plane variables

    # K3s worker nodes (Phase 5)
    k3s_worker_platform:
      hosts:
        # Add your k3s worker hosts here
      vars:
        # K3s worker variables
